# Generated by Django 3.1.2 on 2020-11-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20201030_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='item',
        ),
        migrations.AddField(
            model_name='category',
            name='item',
            field=models.ManyToManyField(related_name='category_item', through='bank.Remove', to='bank.Item'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(related_name='item_category', through='bank.Remove', to='bank.Category'),
        ),
    ]
