# Generated by Django 3.1.2 on 2020-11-18 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20201113_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='bank.category'),
        ),
        migrations.AlterField(
            model_name='remove',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remove_category', to='bank.category'),
        ),
        migrations.AlterField(
            model_name='remove',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remove_item', to='bank.item'),
        ),
    ]
