# Generated by Django 3.1.2 on 2020-11-13 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0002_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unesco.year'),
        ),
    ]
