# Generated by Django 3.1.2 on 2020-11-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0003_auto_20201113_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
